# Parameters
randomf:
  n_estimators: [200] #[10,20,50,100,200,500]
  max_depth: [15] #[null, 5, 15]
  max_features: ['sqrt'] #['sqrt', 'log2']
  criterion: ['absolute_error'] #['squared_error', 'absolute_error']

mlp:
  learning_rate: [0.01] #[0.001,0.01]
  regularization_l2: [0.0] #[0.0,0.01]
  batch_size: [64] #[64, 128]
  num_steps: [5000] #[500,1000,2000,5000]
  num_layers: [3] #[2,3]
  hidden_size: [32] #[32, 64]

drnet:
  learning_rate: [0.001] # [0.001, 0.01]
  regularization_l2: [0.0] #[0.0, 0.01]
  batch_size: [128] #[64, 128]
  num_steps: [5000] #[500, 1000, 2000,5000]
  num_representation_layers: [3] #[2,3]
  num_inference_layers: [1] #[1,2]
  num_bins: [10]
  hidden_size: [64] #[32,64]

vcnet:
  learning_rate: [0.01] #[0.01, 0.001]
  batch_size: [128] #[64,128]
  hidden_size: [64] #[32, 64]
  num_steps: [2000] #[500,1000,2000,5000]

cbrnet:
  learning_rate: [1e-3, 1e-2]
  regularization_l2: [0.0]
  batch_size: [128,256] #[32, 64, 128]
  num_steps: [2000] #[500,1000,2000,5000]
  num_representation_layers: [3] #[2, 3]
  num_inference_layers: [1] #[1, 2]
  regularization_ipm: [0.001,0.01,0.1] #[0.1,0.5]
  num_cluster: [5]
  hidden_size: [32] #[32, 64, 128]


