# Parameters
randomf:
  n_estimators: [200] #[20, 50, 100, 200]
  criterion: ["squared_error"] #["squared_error","absolute_error"]
  max_depth: [null] #[null, 5, 15]
  max_features: ["sqrt"] #[null, 5, 15]

mlp:
  learning_rate: [0.01] #[0.0001,0.001]
  regularization_l2: [0.0] #[0.0,0.01]
  batch_size: [128] #[64, 128]
  num_steps: [5000] #[5000]
  num_layers: [3] #[2,3]
  hidden_size: [32] #[32, 64]

drnet:
  learning_rate: [0.001] #[0.0001,0.001]
  regularization_l2: [0.0] #[0.0,0.1]
  batch_size: [64] #[64,128]
  num_steps: [5000]
  num_representation_layers: [3] #[2,3]
  num_inference_layers: [2] #[1,2]
  num_bins: [10]
  hidden_size: [64] #[32,64]

vcnet:
  learning_rate: [0.001] #[0.01, 0.001]
  batch_size: [32]

cbrnet:
  learning_rate: [0.01]
  regularization_l2: [0.0]
  batch_size: [32] #[32, 64, 128]
  num_steps: [2000] #[500,1000,2000]
  num_representation_layers: [3] #[2, 3]
  num_inference_layers: [1] #[1, 2]
  regularization_ipm: [0.1] #[0.1,0.5]
  num_cluster: [5]
  hidden_size: [32] #[32, 64, 128]


