optimization_settings_list:
  exact: ['exact','heuristic1'] # 'exact', heuristic1,'heuristic2'
  cost_sensitive_optimization: [False] # True, False
  protected_attribute: [23]
  epsilon_disparate_treatment: [1]
  epsilon_disparate_outcome: [1]
  budget_list: [100]
  ntreatments_list: [10]

