optimization_settings_list:
  exact: [True]
  cost_sensitive_optimization: [False]
  protected_attribute: [23]
  epsilon_disparate_treatment: [1]
  epsilon_disparate_outcome: [1]
  budget_list: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250]
  ntreatments_list: [10]
